import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Organism/Header";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { FaUserTie } from "react-icons/fa";
import { Button } from "@/components/ui/button";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex max-w-screen ">
        <Header />
        <main className="flex-grow">
          <div className="w-full min-h-[40px] max-w-[calc(100vh - 224px)] flex md:justify-between justify-end items-center bg-purple-600 px-4 text-white">
            <Breadcrumb className="hidden md:block">
              <BreadcrumbList>
                <BreadcrumbItem>
                  <BreadcrumbLink href="/">Dashboard</BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbSeparator />
                <BreadcrumbItem>
                  <BreadcrumbLink href="/users">Users</BreadcrumbLink>
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
            {/* <div className=" py-0 my-2 px-4 rounded-[50px] border-[1px] border-solid border-gray-200 flex justify-between items-center gap-3"> */}
            <Button className="avatar hover:bg-purple-800">
              <FaUserTie />
            </Button>
            {/* <div className="avatar-info">
                <h4 className="text-sm text-white capitalize pb-0 mb-0 leading-3">Arjun J.</h4>
                <p className="text-[12px] ">Student</p>
              </div> */}
            {/* </div> */}
          </div>
        </main>
      </body>
    </html>
  );
}
