import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/hooks/storeProvider";
import Notification from "@/components/molecule/notification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {
  return (
    <html lang="en">
      <body className="flex max-w-screen justify-center ">
        <StoreProvider>
          <>
            <Notification />
            {children}
          </>
        </StoreProvider>
      </body>
    </html>
  );
}
